# Generated by Django 6.0.5 on 2026-05-24 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('admin', 'Cooperative Admin')], default='farmer', max_length=10)),
                ('farmer_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('passcode', models.CharField(blank=True, max_length=6, null=True)),
                ('coop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.IntegerField()),
                ('analysis_type', models.CharField(default='both', max_length=20)),
                ('quality_score', models.FloatField(default=75.0)),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('trust_score', models.FloatField(default=0.0)),
                ('payment_eligible', models.BooleanField(default=False)),
                ('extracted_amount', models.FloatField(default=0.0)),
                ('extracted_date', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_seller_id', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_invoice_id', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_ocr_lines', models.TextField(default='[]')),
                ('detections', models.TextField(default='[]')),
                ('annotated_image_base64', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisbursementTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='SETTLED', max_length=20)),
                ('gross_amount', models.FloatField(default=0.0)),
                ('fee_percent', models.FloatField(default=1.8)),
                ('fee_amount', models.FloatField(default=0.0)),
                ('net_settlement', models.FloatField(default=0.0)),
                ('reference', models.CharField(max_length=50)),
                ('immutable_hash', models.CharField(max_length=64)),
                ('debit_account', models.CharField(max_length=50)),
                ('credit_account', models.CharField(max_length=50)),
                ('narration', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='core.verificationrecord')),
            ],
        ),
    ]
